[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
futures-util = "0.3.30"
jwt-compact = "0.8.0"
serde = "1.0.204"
serde_json = "1.0.120"
tokio = {version = "1.38.1", features = ["full"]}
tokio-tungstenite = "0.23.1"
